### ISSUE TITLE
Error while displaying Icons

### ISSUE THREAD

**Issue by bgrgv** [undrbridge/curved_drawer#3]
When including icons inside the drawer, this error is thrown :

> TypeError: Cannot read property 'icon' of undefined
See also: https://flutter.dev/docs/testing/errors

This was my code :
```dart
`drawer: CurvedDrawer(
          color: Colors.white,
          width: 75.0,
          items: <DrawerItem>[DrawerItem(icon: Icon(Icons.alarm),label: "Alarm")],
        ),`

**Comment by sonOfwidgets** [comment]
Should be fixed by #5Update curved_drawer.dart

**Comment by bgrgv** [comment]
> Should be fixed by #5Update curved_drawer.dart

@jonathananales it seems to be working now 👍
